rules:

- listen_addr: 
    - "[::]:4443"
  protocol: Tls
  upstreams:
    - name: wstunnel
      match: !Sni ws.erebe.eu
      addrs: 
        - "[fd00:cafe::254]:8084"
      proxy_protocol: false
      cnx_max_duration: 1h

    - name: nginx-https
      match: !Any
      addrs: 
      - "62.210.156.7:80"
      proxy_protocol: false
      cnx_max_duration: 10m
