rules:
- listen_addr: 
    - "[::]:25"
    - "[::]:587"
    - "[::]:993"
  protocol: Tcp
  upstreams:
    - name: smtp
      match: !DestinationPort 25
      addrs: 
        - "[fd00:cafe::5]:25"
      proxy_protocol: true
      cnx_max_duration: 5m

    - name: smtps
      match: !DestinationPort 587
      addrs: 
        - "[fd00:cafe::5]:587"
      proxy_protocol: true
      cnx_max_duration: 5m

    - name: imaps
      match: !DestinationPort 993
      addrs: 
        - "[fd00:cafe::5]:993"
      proxy_protocol: false
      cnx_max_duration: 10m

- listen_addr: 
    - "[::]:443"
  protocol: Tls
  upstreams:
    - name: wstunnel
      match: !Sni ws.erebe.eu
      addrs: 
        - "[fd00:cafe::254]:8084"
      proxy_protocol: false
      cnx_max_duration: 1h

    - name: nginx-https
      match: !Any
      addrs: 
        - "[fd00:cafe::254]:444"
      proxy_protocol: true
      cnx_max_duration: 10m

- listen_addr: 
    - "[::]:80"
  protocol: Tcp
  upstreams:
    - name: nginx-http
      match: !Any
      addrs: 
        - "[fd00:cafe::254]:81"
      proxy_protocol: true
      cnx_max_duration: 10m
