rules:
- listen_addr: 
    - "[::]:25"
    - "[::]:587"
    - "[::]:993"
  protocol: Tcp
  upstreams:
    - name: smtp
      match: !DestinationPort 25
      backends: !Static
        - addr: "[fd00:cafe::5]:25"
      proxy_protocol: true
      cnx_max_duration: 5m
      load_balancing: !RoundRobin

    - name: smtps
      match: !DestinationPort 587
      backends: !Static
        - addr: "[fd00:cafe::5]:587"
      proxy_protocol: true
      cnx_max_duration: 5m
      load_balancing: !RoundRobin

    - name: imaps
      match: !DestinationPort 993
      backends: !Static
        - addr: "[fd00:cafe::5]:993"
      proxy_protocol: false
      cnx_max_duration: 10m
      load_balancing: !RoundRobin

- listen_addr: 
    - "[::]:443"
  protocol: Tls
  upstreams:
    - name: wstunnel
      match: !Sni ws.erebe.eu
      backends: !Static
        - addr: "[fd00:cafe::254]:8084"
      proxy_protocol: false
      cnx_max_duration: 1h
      load_balancing: !RoundRobin

    - name: nginx-https
      match: !Any
      backends: !Static
        - addr: "[fd00:cafe::254]:444"
      proxy_protocol: true
      cnx_max_duration: 10m
      load_balancing: !RoundRobin

- listen_addr: 
    - "[::]:80"
  protocol: Tcp
  upstreams:
    - name: nginx-http
      match: !Any
      backends: !Static
        - addr: "[fd00:cafe::254]:81"
      proxy_protocol: true
      cnx_max_duration: 10m
      load_balancing: !RoundRobin

- listen_addr:
  - "[::]:8089"
  protocol: Tls
  upstreams:
    - name: test
      match: !Any
      backends: !Static
        - addr: "[2a01:4f8:0:a232::2]:80"
      proxy_protocol: false
      cnx_max_duration: 10m
      load_balancing: !RoundRobin
      tls:
        certificate: /etc/certs.d/erebe.eu/tls.crt
        private_key: /etc/certs.d/erebe.eu/tls.key
        alpns: ["h2"]
